apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: solar-system
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
